#!/bin/bash
#
# This script is run as root before showing login widget.

set -x

OUTPUTS=($(xrandr -q | grep connected | grep -v disconnected | cut -f1 -d " "))

# If Composite is our only output, enable it
if [ ${#OUTPUTS[@]} -eq 1 ]; then
  # Set padding for apropriate video mode
  if [[ ! -z $(xrandr -q | grep '*' | grep 'PAL') ]]; then
    COMP_STATE="--mode PAL10"
  else
    COMP_STATE="--mode NTSC10"
  fi
else
  COMP_STATE=--off
fi

for OUTPUT in "${OUTPUTS[@]}"; do
  if [[ $OUTPUT  == Composite-* ]]; then
    COMPOSITE=$OUTPUT
  else
    EXTERNAL=$OUTPUT
  fi
done

if [[ ! -z "$COMPOSITE" ]]; then
  echo "xrandr --output $COMPOSITE $COMP_STATE" >>/var/log/Xsetup.log
  xrandr --output $COMPOSITE $COMP_STATE
fi

if [[ ! -z "$EXTERNAL" ]]; then
  echo "xrandr --output $EXTERNAL --auto" >>/var/log/Xsetup.log
  xrandr --output $EXTERNAL --auto
  echo "xrandr --output $EXTERNAL --auto" >>/var/log/Xsetup.log
  xrandr --output $EXTERNAL --auto
  xsetroot -cursor_name top_left_arrow
fi
