#!/bin/sh

set -e

# conffile still present, but mkimage removed
if ! which mkimage >/dev/null 2>&1; then
    exit 0
fi

# ignored
initrd="$2"
echo "Generating U-Boot image from $initrd"
exec mkimage -A arm -T ramdisk -C none -d "$initrd" /boot/initrd.uimage
